### ISSUE TITLE
Could not clone the repo in windows machine

### ISSUE THREAD

**Issue by ashokkumarsundar** [StrangerealIntel/DailyIOC#4]
Could not clone the repository in windows. Got the following issue:

Cloning into 'StrangerealIntel'...
remote: Enumerating objects: 1341, done.
remote: Counting objects: 100% (565/565), done.
remote: Compressing objects: 100% (468/468), done.
Receiving objects:  85% (1140/1341), 332.01 KiB | 60remote: Total 1341 (delta 170), reused 0 (dReceiving objects:  86% (1154/1341), 332.01 KiB | 601.00 KiB/s
Receiving objects: 100% (1341/1341), 781.07 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (436/436), done.
error: invalid path '18-11-19/APT organization "pat the bear" report on the Palestinian government attack.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.        
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

There is a double quote in the following file name that could be the problem.
DailyIOC/18-11-19/APT organization "pat the bear" report on the Palestinian government attack.md

**Comment by StrangerealIntel** [comment]
I changed the name of file, you can confirm to me if it works or need to change something else.
Nice day / evening to you

**Comment by ashokkumarsundar** [comment]
Thanks @StrangerealIntel I can clone the repo now.
