### ISSUE TITLE
Need the license information to the repo

### ISSUE THREAD

**Issue by ashokkumarsundar** [StrangerealIntel/DailyIOC#5]
I couldn't not find the license information regarding the usage of this repo.

Please add it, so people can use this repo legally.

**Comment by rbnor** [comment]
Are you serious?

**Comment by StrangerealIntel** [comment]
Hi, all the data in the repository come either from public sources or from my research, everything is copyright free and is made available to everyone to improve the security of their information systems / AV software.
Have fun with it  ;-)
Greetings

**Comment by ashokkumarsundar** [comment]
Thanks @StrangerealIntel and @rbnor if possible please add a file like this:
https://github.com/advanced-threat-research/Yara-Rules/blob/master/LICENSE
